mod_pbxproj.py
this will make the script work with swift source file
=> added swift source file awareness

mod_pbxproj.py
Added a command line interface to modify only compilation flags (add or remove) in a particular configuration (debug, release or both)
=> Flags and command-line functionality

mod_pbxproj.py
This implementation does the sort in _printNewXCodeFormat, just before objects are written to a file.
=> sort the children of the PBXGroup, so that all items in the Xcode project navigator are sorted

mod_pbxproj.py
Just added a boolean param to add_run_script to provide the possibility to insert the script build phase before the compile one.
=> Provide the possibility to insert a script build phase before the compile one

mod_pbxproj.py
Added from the issue report: #32
=> add remove_by_path method

mod_pbxproj.py
=> add support for coredata files

mod_pbxproj/__init__.py
=> fix: module initialization

mod_pbxproj/mod_pbxproj.py
Add support for .tbd libs, which is introduced by Xcode7.
=> Add support for .tbd libs

mod_pbxproj/mod_pbxproj.py, readme.md
Target parameter let added file to be included only on specified target
name, instead of all targets.
=> Added target parameter to add_file

mod_pbxproj/mod_pbxproj.py
This is necessary to add compiler configuration to particular files.
=> Added method to fetch keys by file name

mod_pbxproj/mod_pbxproj.py, readme.md
Updates README and cleans up method names from #78 , also adds a remove method. I don't use python often, but I tested this against my own project and it functions as expected..
=> Allow setting flags like ENABLE_BITCODE and CLANG_ENABLE_MODULES

mod_pbxproj/mod_pbxproj.py
These files should be compiled.
=> Add dtrace files to the sources build list.

mod_pbxproj/mod_pbxproj.py
It was already added to add_file, so just passing it on
=> Adding target argument to add_file_if_doest_exist

mod_pbxproj/mod_pbxproj.py
Storyboard files, when compiled, are "special" files like frameworks, etc - they are folders to be treated as files.
=> Adds support for compiled storyboard (.storyboardc) files

pbxproj/pbxextensions/ProjectFlags.py, pbxproj/pbxsections/XCBuildConfiguration.py
Fix for #125, @eAi please confirm solution
=> fix: add set_flags method to allow the code sign to work as expected.

pbxproj/pbxextensions/ProjectFlags.py, pbxproj/pbxsections/PBXLegacyTarget.py, pbxproj/pbxsections/PBXNativeTarget.py, pbxproj/pbxsections/XCBuildConfiguration.py, pbxproj/pbxsections/__init__.py
Fixes issue #122 . @yodutouf please confirm solution to work
=> Missing PBXLegacyTarget type

pbxproj/pbxsections/PBXGenericTarget.py, tests/pbxextensions/TestProjectFiles.py
=> fix: add header file fails due to unhandled buildphase type

pbxproj/pbxextensions/ProjectFiles.py, tests/pbxextensions/TestProjectFiles.py
=> fix: code-sign errors by adding flags when were not necessary

pbxproj/PBXGenericObject.py, pbxproj/__init__.py, pbxproj/pbxsections/PBXProject.py, tests/pbxsections/TestPBXProject.py
=> fix: issue with projectReferences

pbxproj/pbxextensions/ProjectFiles.py, pbxproj/pbxsections/PBXContainerItemProxy.py, pbxproj/pbxsections/PBXFileReference.py, pbxproj/pbxsections/PBXGroup.py, pbxproj/pbxsections/PBXReferenceProxy.py, pbxproj/pbxsections/__init__.py, tests/pbxextensions/TestProjectFiles.py, tests/samplescli/dependency.xcodeproj/project.pbxproj
Additionally, the products of the child project can be added automatically into the parent project. It has been tested against frameworks and bundles. Solves #156.
=> feat: add xcode project into another xcode project. 

.travis.yml, mod_pbxproj.py, pbxproj/PBXGenericObject.py, pbxproj/PBXKey.py, pbxproj/PBXObjects.py, pbxproj/pbxcli/__init__.py, pbxproj/pbxextensions/ProjectFiles.py, pbxproj/pbxsections/PBXGroup.py, setup.py, tests/pbxcli/TestPBXCLI.py, tests/pbxextensions/TestProjectFiles.py
#101  @alexk403 @rublevma could you verify this branch to be compatible with 3.5?
=> Python3 support

pbxproj/PBXGenericObject.py, tests/TestPBXGenericObject.py
=> fix: escaping of single quotes

pbxproj/pbxextensions/ProjectFiles.py
=> Supported the jpg files

pbxproj/pbxextensions/ProjectFiles.py
=> Add support for .mlmodel and .html files.

setup.py
Doing so makes it look better on the pypi website.
=> setup.py: add readme on pypi (long_description)

pbxproj/pbxextensions/ProjectFiles.py, tests/pbxextensions/TestProjectFiles.py
PR to address bug in #225 
@ynechaev please confirm that this will address your issue.
=> fix: add_files with force false will ignore the targets where the file is present

pbxproj/pbxextensions/ProjectFiles.py, tests/pbxcli/TestPBXProjFolder.py, tests/pbxextensions/TestProjectFiles.py
=> fix: escape search paths with whitespaces when adding libs/frameworks

pbxproj/XcodeProject.py, pbxproj/pbxextensions/ProjectFiles.py, tests/pbxcli/TestPBXCLI.py, tests/samplescli/broken-references.pbxproj
=> fix: made code more resilient to missing/broken references

pbxproj/pbxextensions/ProjectFlags.py, pbxproj/pbxsections/PBXShellScriptBuildPhase.py, tests/pbxextensions/TestProjectFlags.py
=> feat: allow to add input/output files to run script build phases

pbxproj/PBXObjects.py, pbxproj/pbxextensions/ProjectFlags.py, tests/pbxextensions/TestProjectFlags.py
=> feat: add methods to add/remove flags to the root project

pbxproj/pbxextensions/ProjectFlags.py, pbxproj/pbxsections/PBXShellScriptBuildPhase.py, tests/pbxextensions/TestProjectFlags.py
PR to allow "For install build only" to be checked/unchecked on Run Script phase
Added tests
=> Enable runOnlyForDeploymentPostprocessing flag
